#python learning Notes 
Learn python basics when learning packages

## built-in functions

#### range(a, b)

In [2]:
# include left, exclude right!
range(1,13)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

####enumerate( list )

In [3]:
# return index and list value, as a tuple
for i, month in enumerate(range(1, 13)):
    print i, month

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
10 11
11 12


## numpy functions

In [10]:
import numpy as np

#### flatten(order)
order: defult is 'C', means row-major, while 'F' means Fortran-like column-major

In [12]:
axes = np.array([[1,2],[3,4]])
print axes 

print '\n'+'after flatten:'
print axes.flatten()
print '\n'+'Fortran-like:'
print axes.flatten('F')

[[1 2]
 [3 4]]

after flatten:
[1 2 3 4]

Fortran-like:
[1 3 2 4]


#### mean( )

if parameter keeps empty, mean over all dimensions.

In [20]:
X = np.array([[1,2],[4,5]])
print X.mean()
print X.mean(0)

3.0
[ 2.5  3.5]


In [68]:
l = [4,2,55,6,4,3,6,7,8,43,5,3,1]

In [45]:
def e(var, l=[]):
    l.append(var)
    return l

In [64]:
for i in range(len(l)):
    for j in range(len(l)):
        if l[i]>l[j]:
            l[i],l[j] = (l[j],l[i])
            

In [66]:
def quicksort(data, low = 0, high = None):
    if high == None:
        high = len(data) - 1
    if low < high:
        s, i, j = data[low], low, high
        while i < j:
            while i < j and data[j] >= s:
                j = j - 1
            if i < j:
                data[i] = data[j]
                i = i + 1
            while i < j and data[i] <= s:
                i = i + 1
            if i < j:
                data[j] = data[i]
                j = j - 1
        data[i] = s
        quicksort(data, low, i - 1)
        quicksort(data, i + 1, high)

In [69]:
quicksort(l)

In [70]:
l

[1, 2, 3, 3, 4, 4, 5, 6, 6, 7, 8, 43, 55]

In [73]:
d = {'a':123,'b':432, 6:'wht'}

In [75]:
'a' in d 

True

In [77]:
del d['b']

In [78]:
d


{6: 'wht', 'a': 123}

In [79]:
d['b']=421

In [80]:
d

{6: 'wht', 'a': 123, 'b': 421}

In [100]:
for i,j in zip('abcdef',[1,2,3,4,5,6]):
    d[i] = j
d

{6: 'wht', 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

In [102]:
for key in d:
    print key,

a c b e d 6 f


In [84]:
dict([(1,2),(4,5)])


{1: 2, 4: 5}

In [85]:
tups = [(1,2,3),(4,5,6)]

In [86]:
[[x for x in tup] for tup in tups]

[[1, 2, 3], [4, 5, 6]]

In [87]:
[x for tup in tups for x in tup]

[1, 2, 3, 4, 5, 6]

In [90]:
list(list([1,23,4]))==[1,23,4]

True

In [92]:
pwd

u'/home/ek777/Documents/Downscaling/Climate-Downscaling'

In [93]:
%ls

cdms2-learning.ipynb               scaler_slp.pkl
dset_from_dict.nc                  scikit-learnning-EOF.ipynb
EOF.pkl                            show_station_location_map.ipynb
ersst.201507.nc                    station_data_preprocess.ipynb
iris-learning-1.ipynb              station_data_preprocess_KZ.ipynb
python-LearningWithLearning.ipynb  testfile.txt
README.md                          xray-learning.ipynb


In [94]:
f = open('testfile.txt')

In [98]:
[x.rstrip() for x in f]

[]